name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        modules: 'core widgets network'
    - name: qmake
      run: qmake src/
    - name: make
      if: runner.os == 'macOS'
      run: make
    - name: nmake
      if: runner.os == 'Windows'
      run: nmake.exe 
