name: C/C++ CI

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: jurplel/install-qt-action@v2
      with:
        modules: 'core gui widgets network qml quick quickcontrols2 xml'

    - name: configure
      run: cmake -S . -B build

    - name: build
      run: cmake --build build --config Release

    - name: deploy win
      run: windeployqt --release --qmldir gui --compiler-runtime --verbose 2 build/src/bin/Release/OscMackieControl.exe
      if: runner.os == 'Windows'

    - name: deploy mac
      run: macdeployqt build/src/bin/OscMackieControl.app -qmldir=gui -verbose=3
      if: runner.os == 'macOS'

    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: release-${{ runner.os }}
        path: build/src/bin