name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: AutoModality/action-clean@v1
    - name: get the repo
      uses: actions/checkout@v2
      with:
        submodules: true

    # - name: get cmake
    #   uses: lukka/get-cmake@latest   

    - name: configure windows env
      uses: ilammy/msvc-dev-cmd@v1

    - name: install qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        modules: 'core widgets network'


    - name: qmake osc
      run: qmake OSC.pro
      working-directory: thirdParty/osc-cpp-qt

    - name: nmake osc
      run: nmake.exe
      working-directory: thirdParty/osc-cpp-qt


    - name: cmake rtmidi
      run: cmake -G"NMake Makefiles" .
      working-directory: thirdParty/rtmidi

    - name: nmake rtmidi
      run: nmake.exe
      working-directory: thirdParty/rtmidi


    - name: qmake
      run: qmake src/

    - name: nmake
      run: nmake.exe

    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: release-windows
        path: build/release





  build-macos:
    runs-on: macOS-latest

    steps:
    - uses: AutoModality/action-clean@v1
    - name: get the repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: install qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        modules: 'core widgets network'


    - name: qmake osc
      run: qmake OSC.pro
      working-directory: thirdParty/osc-cpp-qt

    - name: make osc
      run: make
      working-directory: thirdParty/osc-cpp-qt


    - name: cmake rtmidi
      run: cmake .
      working-directory: thirdParty/rtmidi

    - name: make rtmidi
      run: make
      working-directory: thirdParty/rtmidi


    - name: qmake
      run: qmake src/

    - name: make
      run: make

    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: release-macos
        path: build/release
      
