name: Test Selfhost

on:
  push:
    branches: [ master ]

jobs:
  test-self-host:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: get the repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: install qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        install-deps: false
        modules: 'core widgets network'


    - name: qmake osc
      run: qmake OSC.pro
      working-directory: thirdParty/osc-cpp-qt

    - name: make osc
      run: make
      working-directory: thirdParty/osc-cpp-qt


    - name: cmake rtmidi
      run: cmake .
      working-directory: thirdParty/rtmidi

    - name: make rtmidi
      run: make
      working-directory: thirdParty/rtmidi


    - name: qmake
      run: qmake src/

    - name: make
      run: make
      
  test-self-host2:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: AutoModality/action-clean@v1
    - name: get the repo
      uses: actions/checkout@v2
      with:
        submodules: true 

    - name: install qt
      uses: jurplel/install-qt-action@v2.6.2
      with:
        install-deps: false
        modules: 'core widgets network'


    - name: qmake osc
      run: qmake OSC.pro
      working-directory: thirdParty/osc-cpp-qt

    - name: make osc
      run: make
      working-directory: thirdParty/osc-cpp-qt


    - name: cmake rtmidi
      run: cmake .
      working-directory: thirdParty/rtmidi

    - name: make rtmidi
      run: make
      working-directory: thirdParty/rtmidi


    - name: qmake
      run: qmake src/

    - name: make
      run: make
